site_name: System Design Mentor
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Configuration: configuration.md
  - Design: design.md
theme:
  name: material
plugins:
  - search
extra:
  repo_name: system-design-reviewer
  repo_url: https://github.com/atieqrehman11/system-design-reviewer
